version: "3.9"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - 3001:3000
    networks:
      - app
networks:
  app:
    external: true
    name: app