{
 "title": "Node Backend",
 "description": "Monitor an application built using Apollo Server",
 "tags": [
  "nodejs",
  "apollo",
  "backend"
 ],
 "time": { "from": "2021-12-05T19:15:20.274Z", "to": "2021-12-05T23:24:12.450Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(apollo_server_starting, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(apollo_server_starting, instance)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(apollo_server_starting, hostname)"
    }
   },
   {
    "name": "requestTarget",
    "label": "Request Target",
    "query": "0.001,0.005,0.015,0.05,0.1,0.2,0.3,0.4,0.5,1,5,10"
   },
   {
    "name": "requestTolerance",
    "label": "Request Tolerance",
    "query": "0.001,0.005,0.015,0.05,0.1,0.2,0.3,0.4,0.5,1,5,10"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Error Rate",
   "type": "stat",
   "description": "The percentage of requests that errored.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(apollo_query_failed{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"} OR on() vector(0)) / sum(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"})) * 100",
     "legendFormat": "Failed %"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "stat",
   "description": "Requests per second for the selected interval.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "description": "Apdex score calculated using the selected request target and request tolerance.\n\nFor more information, please visit https://en.wikipedia.org/wiki/Apdex.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", le=\"$requestTarget\", success=\"true\"}) + (sum(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", le=\"$requestTolerance\", success=\"true\"}) - sum(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", le=\"$requestTarget\", success=\"true\"})) / 2) / sum(apollo_query_duration_count{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", success=\"true\"})) * 100",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "description": "Number of received requests.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"})",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "graph",
   "description": "Response latency for the selected interval.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval])) by (instance, hostname, le))",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apollo_query_duration_bucket{job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "description": "Requests per second for the selected interval.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval])) by (instance, hostname)",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "User CPU - {{instance}} - {{hostname}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "System CPU - {{instance}} - {{hostname}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "Total CPU - {{instance}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "Process Memory - {{instance}} - {{hostname}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "Heap Total - {{instance}} - {{hostname}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "Heap Used - {{instance}} - {{hostname}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "External Memory - {{instance}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "description": "Errors per second for the selected interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval])) by (instance, hostname)",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nodejs_active_handles" }
   ]
  }
 ]
}